Moved every function into pipline functions.py and pipeline constuctor into pipeline.py
P6-AAU-23/server pull request #74
Opened 2023-05-03 11:24 UTC by thom776g

2023-05-03 11:30 UTC, feybelle submitted a review, later dismissed

2023-05-03 12:30 UTC, feybelle submitted a review, later dismissed

2023-05-03 18:00 UTC, CasperStaahl requested changes
Kan vi samle handler klasserne og deres tilhørende funktioner i samme klasse og så fjerne pipeline_functions.py?

2023-05-05 11:34 UTC, CasperStaahl approved these changes
lgtm

2023-05-05 11:36 UTC, merged